---
LOGGING:
    ENABLED: true
    TOFILE: true
    LOGLEVEL: "DEBUG"
MODEM:
    ENABLED: true
    NAME: "Huawei"
    ADDRESS: "127.0.0.1"
DATABASE:
    ENABLED: true
    NAME: "InfluxDB"
    ADDRESS: "localhost"
    PORT: 8086
SPEEDTEST:
    ENABLED: true
    NAME: "Ookla"